var datae = {
  MerchantID: "2000132",
  MerchantTradeNo: "121212121212",
  MerchantTradeDate: "2016/04/21 02:00:57",
  PaymentType: "aio",
  TotalAmount: "1",
  TradeDesc: "1",
  ItemName: "1",
  ReturnURL: "http://localhost:3000",
  ChoosePayment: "Credit",
  // CheckMacValue
  ClientBackURL: "",
  ItemURL: "",
  Remark: "",
  ChooseSubPayment: "",
  OrderResultURL: "",
  NeedExtraPaidInfo: "",
  DeviceSource: "",
  IgnorePayment: "",
  PlatformID: "",
  InvoiceMark: "",
  HoldTradeAMT: "",
  EncryptType: "",
  UseRedeem: "",
  CreditInstallment: "",
  InstallmentAmount: "",
  Redeem: "",
  UnionPay: "",
  Language: ""
};
